name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  check-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH Key exists
        run: test -n "${{ secrets.SSH_PRIVATE_KEY }}" && echo "Key exists" || echo "Key is empty"

      - name: Test connection
        id: ssh_test
        uses: appleboy/ssh-action@master
        with:
          host: 193.239.161.50
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo " "

      - name: Check connection result
        run: |
          echo "Test connection..."
          if [ "${{ steps.ssh_test.outcome }}" == "success" ]; then
            echo "Connection successful"
          else
            echo "Connection failed"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-connection
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 193.239.161.50
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cmd /c "echo Stopping old service... >> C:\ASGBuilds\deploy.log"
            cmd /c "sc stop ASGService || echo Service not found >> C:\ASGBuilds\deploy.log"
            cmd /c "sc delete ASGService || echo Service not found >> C:\ASGBuilds\deploy.log"
            
            cmd /c "echo Deploying new version... >> C:\ASGBuilds\deploy.log"
            cmd /c "rmdir /s /q C:\ASGBuilds || echo Folder not found >> C:\ASGBuilds\deploy.log"
            cmd /c "mkdir C:\ASGBuilds"
            
            cmd /c "git clone https://github.com/KeFFiA/ASG.git C:\ASGBuilds"
            
            cmd /c "cd C:\ASGBuilds && python -m venv venv && .\venv\Scripts\pip install -r requirements.txt"
            
            cmd /c "echo Creating service... >> C:\ASGBuilds\deploy.log"
            cmd /c "sc create ASGService binPath= \"C:\ASGBuilds\venv\Scripts\python.exe C:\ASGBuilds\main.py\" start= auto"
            
            cmd /c "echo Starting service... >> C:\ASGBuilds\deploy.log"
            cmd /c "sc start ASGService >> C:\ASGBuilds\deploy.log"
