name: Deploy to Windows Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.ASG_SERVER }}
        key-file: C:\Users\Administrator\.ssh\github-actions-key

    - name: Configure SSH Environment
      run: |
        New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh"
        
        ssh-keyscan -t ed25519 193.239.161.50 | Out-File -Append -FilePath "$env:USERPROFILE\.ssh\known_hosts"
        
        icacls "C:\Users\Administrator\.ssh\github-actions-key" /reset
        icacls "C:\Users\Administrator\.ssh\github-actions-key" /grant:r "$env:USERNAME:(R)"
        icacls "C:\Users\Administrator\.ssh\github-actions-key" /inheritance:r

    - name: Deploy and Restart
      run: |
        $commands = @(
            "cd C:\ASGBuilds",
            "git pull origin master",
            "python -m pip install --upgrade pip",
            "pip install -r requirements.txt",
            "taskkill /IM python.exe /F /T",
            "start /B python main.py"
        )
        
        ssh -i "C:\Users\Administrator\.ssh\github-actions-key" Administrator@193.239.161.50 "$($commands -join ' && ')"