name: Deploy to Windows Server

on:
  push:
    branches:
      - master

jobs:
  check-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSH Key exists
        run: test -n "${{ secrets.SSH_PRIVATE_KEY }}" && echo "Key exists" || echo "Key is empty"

      - name: Test connection
        id: ssh_test
        uses: appleboy/ssh-action@master
        with:
          host: 193.239.161.50
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Connection successful"

      - name: Check connection result
        run: |
          if [ "${{ steps.ssh_test.outcome }}" == "success" ]; then
            echo "Connection successful"
          else
            echo "Connection failed"
            exit 1
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: check-connection
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 193.239.161.50
          username: Administrator
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Stopping old service..."
            sc stop ASGService || echo "Service not found"
            sc delete ASGService || echo "Service not found"
            
            echo "Deploying new version..."
            rmdir /s /q C:\ASGBuilds || echo "Folder not found"
            mkdir C:\ASGBuilds
            
            git clone https://github.com/KeFFiA/ASG.git C:\ASGBuilds
            
            cd C:\ASGBuilds
            python -m venv venv
            .\venv\Scripts\pip install -r requirements.txt
            
            echo "Creating service..."
            sc create ASGService binPath= "C:\ASGBuilds\venv\Scripts\python.exe C:\ASGBuilds\main.py" start= auto
            
            echo "Starting service...."
            sc start ASGService
