name: Deploy to Windows Server

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: windows-latest  # Меняем на Windows runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.ASG_SERVER }}

    - name: Configure SSH
      run: |
        New-Item -ItemType Directory -Force -Path "$env:USERPROFILE\.ssh"
        ssh-keyscan -t ed25519 193.239.161.50 | Out-File -Append "$env:USERPROFILE\.ssh\known_hosts"
        icacls "$env:USERPROFILE\.ssh\github-actions-key" /reset /grant:r "$env:USERNAME:(R)"

    - name: Deploy Application
      run: |
        $commands = @(
            "echo '🛑 Остановка старого сервиса...'",
            "sc stop ASGService || echo 'Сервис уже остановлен'",
            "sc delete ASGService || echo 'Сервис не найден'",
            "echo '📦 Очистка старого кода...'",
            "rmdir /s /q C:\ASGBuilds || echo 'Папка не найдена'",
            "mkdir C:\ASGBuilds",
            "echo '⬇️ Клонирование нового кода...'",
            "git clone https://github.com/KeFFiA/ASG.git C:\ASGBuilds",
            "echo '🐍 Установка зависимостей...'",
            "cd C:\ASGBuilds",
            "python -m venv venv",
            "call .\venv\Scripts\activate",
            "pip install -r requirements.txt",
            "echo '🔧 Создание Windows-службы...'",
            "sc create ASGService binPath= '\""C:\ASGBuilds\venv\Scripts\python.exe\"" C:\ASGBuilds\main.py' start= auto",
            "echo '🚀 Запуск сервиса...'",
            "sc start ASGService",
            "echo '✅ Деплой завершен!'"
        )
        ssh -i "$env:USERPROFILE\.ssh\github-actions-key" Administrator@193.239.161.50 "$($commands -join '; ')"