name: Deploy to Windows Server

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.ASG_SERVER }}

    - name: Deploy and Restart
      run: |
        ssh -o StrictHostKeyChecking=no Administrator@193.239.161.50 '
          cd C:\ASGBuilds
          git pull origin master
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          Stop-Process -Name "python" -Force -ErrorAction SilentlyContinue
          Start-Process python -ArgumentList "main.py" -WindowStyle Hidden
        '